/**
 * Antigravity AI Blog Copywriting Client (Gemini API Integration)
 */
(function (global) {
  'use strict';

  const GEMINI_KEY_STORAGE = 'sns_gemini_api_key';

  function getGeminiKey() {
    return localStorage.getItem(GEMINI_KEY_STORAGE) || '';
  }

  function saveGeminiKey(key) {
    if (key) {
      localStorage.setItem(GEMINI_KEY_STORAGE, key.trim());
    } else {
      localStorage.removeItem(GEMINI_KEY_STORAGE);
    }
  }

  /**
   * Translate Markdown to plain HTML for clipboard rich text pasting
   */
  function mdToHtml(md) {
    if (!md) return '';
    let html = md;
    
    // Note: We don't escape HTML characters here to preserve HTML tags (like <div>, <a>, <table>, etc.) 
    // generated by the AI model for rich copy-pasting.

    // Headings
    html = html.replace(/^### (.*?)$/gm, '<h3 style="font-size: 16px; font-weight: 700; color: #1e1b4b; margin-top: 16px; margin-bottom: 8px;">$1</h3>');
    html = html.replace(/^## (.*?)$/gm, '<h2 style="font-size: 18px; font-weight: 800; color: #1e1b4b; margin-top: 20px; margin-bottom: 10px; border-left: 4px solid #7c3aed; padding-left: 8px;">$1</h2>');
    html = html.replace(/^# (.*?)$/gm, '<h1 style="font-size: 22px; font-weight: 800; color: #111827; margin-bottom: 12px;">$1</h1>');
    
    // Bold
    html = html.replace(/\*\*(.*?)\*\*/g, '<strong style="font-weight: 700; color: #7c3aed;">$1</strong>');
    
    // Horizontal rule
    html = html.replace(/^---$/gm, '<hr style="border: 0; border-top: 1px solid #e5e7eb; margin: 16px 0;">');

    // Bullet Lists
    html = html.replace(/^\* (.*?)$/gm, '<li style="margin-left: 20px; margin-bottom: 4px; list-style-type: disc;">$1</li>');
    html = html.replace(/^- (.*?)$/gm, '<li style="margin-left: 20px; margin-bottom: 4px; list-style-type: disc;">$1</li>');

    // Wrap single list items if any
    
    // Images formatting (alt to caption)
    html = html.replace(/!\[(.*?)\]\((.*?)\)/g, '<div style="text-align: center; margin: 20px 0;"><img src="$2" alt="$1" style="max-width: 90%; height: auto; border-radius: 8px; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1);"><p style="font-size: 12px; color: #6b7280; margin-top: 6px; font-style: italic;">▲ $1</p></div>');

    // Links (Affiliate Links formatting)
    html = html.replace(/\[(.*?)\]\((.*?)\)/g, '<a href="$2" target="_blank" style="color: #2563eb; font-weight: 700; text-decoration: underline;">$1</a>');
    
    // Paragraphs / Breaks
    html = html.replace(/\n\n/g, '<br><br>');
    html = html.replace(/\n/g, '<br>');

    // Clean up invalid <br> tags inside/around tables that might be introduced by newline replacement
    html = html.replace(/(<table[^>]*>|<tr[^>]*>|<td[^>]*>|<tbody>|<\/table>|<\/tbody>|<\/tr>|<\/td>)\s*(?:<br\s*\/?>\s*)+/gi, '$1');
    html = html.replace(/(?:<br\s*\/?>\s*)+(<\/table>|<\/tbody>|<\/tr>|<\/td>)/gi, '$1');

    return html;
  }

  /**
   * Call Google Gemini API to generate the post content
   */
  async function generatePost(productData, style = 'review', customLink = '') {
    const key = getGeminiKey();
    if (!key) {
      throw new Error('Gemini API Key가 설정되지 않았습니다. 상단 입력창에 등록해 주세요.');
    }

    const model = 'gemini-3.5-flash';
    const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${key}`;

    const optionDescriptions = productData.options && productData.options.length > 0
      ? productData.options.join(', ')
      : '없음';

    const affiliateLink = customLink.trim() || productData.link || '#';
    const imageUrls = productData.images && productData.images.length > 0
      ? productData.images.slice(0, 10) // Use up to 10 main images
      : [];

    let imageInstruction = '';
    if (imageUrls.length > 0) {
      imageInstruction = `
[이미지 삽입 지침]
다음은 수집된 상품 이미지 URL 목록입니다:
${imageUrls.map((url, idx) => `- 이미지 ${idx + 1}: ${url}`).join('\n')}

원고 중간중간 (서론 공감대 형성 이후, 스펙 비교 분석 중간, 실사용 후기 소개 시점 등) 문맥이 끝나는 문단 사이에 총 2~3회에 걸쳐 이미지 태그 \`<img src="이미지 URL" alt="이미지 설명">\`을 골고루 분산시켜 삽입해 주세요. 
이미지 설명(alt text)은 검색 노출에 도움되도록 해당 이미지에 어울리는 풍부한 한국어 설명으로 적어주세요. 반드시 제공된 실제 URL만 정확히 사용해야 합니다.
`;
    }

    const isToss = productData.platform === 'toss' || (affiliateLink && affiliateLink.includes('toss.im'));
    const disclosureText = isToss 
      ? "이 포스팅은 토스쇼핑 쉐어링크 활동의 일환으로, 이에 따른 일정액의 수수료를 제공받습니다."
      : "이 포스팅은 쿠팡 파트너스 활동의 일환으로, 이에 따른 일정액의 수수료를 제공받습니다.";

    const systemPrompt = `
당신은 20년 경력의 전문 블로거이자 SEO/AEO/GEO 전문가, 그리고 SNS 마케팅 카피라이팅 전문가입니다. 제공된 상품 정보를 분석하여 고전환율을 이끌어내는 글을 작성하세요.
철저히 기계적인 번역투나 딱딱한 인공지능 말투(예: '도움이 되셨길 바랍니다', '이상으로', '자, 시작해볼까요?' 등)를 금지하고, 실제 이웃이 써보고 친근하게 추천해주는 듯한 구어체로 작성하세요.

출력 형식은 반드시 아래 형식을 정확히 지켜주세요 (각 태그 필수 포함):
[제목]
여기에 블로그 제목 작성 (키워드 최적화 및 궁금증 유발 조합)
[BLOGSPOT_START]
여기에 블로그 본문 내용 작성
[BLOGSPOT_END]

[블로그스팟 (Blogspot) 지침]
- 전체 본문 분량은 반드시 공백 제외 최소 2,000자 이상의 충분하고 상세한 글쓰기를 수행합니다.
- HTML 편집 모드에 바로 붙여넣도록 최소 HTML 태그만 활용합니다. (<html>, <head>, <body>, <script>, <style> 절대 금지. <h2>, <h3>, <p>, <strong>, <ul>, <ol>, <li>, <table>, <tr>, <th>, <td>, <div>, <a> 위주 사용)
- 본문 안에는 <h1>을 절대 사용하지 않고, <h2> 소제목으로 바로 시작하며 "서론", "본론", "결론" 같은 단어는 사용하지 않습니다.
- 소제목은 가급적 독자가 궁금해하는 질문형 구조(예: '1. [상품명], 실제로 사용했을 때 흡입력은 어느 정도였을까요?')로 작성하세요.
- 질문 소제목 바로 아래 첫 문단에는 <strong> 태그를 활용해 2~3줄 이내의 명확한 두괄식 결론 답변을 먼저 제시한 후 상세 설명을 이어갑니다. (AEO/GEO 최적화)
- 상품의 상세 스펙, 장점, 단점을 일목요연하게 파악할 수 있는 깔끔한 HTML <table>(표) 구조를 포함시킵니다.
- 실제 사람이 쓴 내돈내산 찐후기 느낌을 살리기 위해, 1~2가지의 아쉬운 단점을 명확히 짚은 후 '하지만 이런 단점은 ~한 방법이나 실전 팁으로 쉽게 극복할 수 있습니다' 라는 극복 방안을 반드시 덧붙이세요.
- 본문 중간이나 하단에 '구매 전 스마트 체크' 또는 '실수를 줄이는 스마트 팁' 등 독창적인 노하우를 담은 스마트 팁 섹션을 포함시킵니다.
- **제휴 수수료 안내 문구 규칙**: 반드시 전체 본문 내용의 맨 아래 마지막([BLOGSPOT_END] 바로 직전)에 가운데 정렬(Center)로 작성하고, 다른 폰트 스타일을 적용하세요. (예: 11px 크기, 옅은 회색 #888888, 이탤릭체, 본문 서체와 구분되는 서체 적용). HTML 예시:
  <p style="text-align: center; font-size: 11px; color: #888888; font-style: italic; font-family: 'Malgun Gothic', 'Apple SD Gothic Neo', sans-serif; margin-top: 30px;">${disclosureText}</p>
- **제품 구매 링크 규칙**: 제휴 수수료 안내 문구 바로 위에는 클릭하여 제품 상세 정보나 후기 페이지로 넘어가고 싶게 만드는 매력적이고 직관적인 버튼형 제품 링크를 반드시 삽입해 주세요. (네이버 블로그 복사 붙여넣기 시 서식이 깨지는 것을 방지하기 위해 반드시 아래 예시와 같이 <table> 태그를 활용한 버튼 구조를 그대로 작성해야 합니다.) HTML 예시:
  <table align="center" style="border-collapse:collapse;margin:35px auto 25px auto;background:linear-gradient(90deg,#f97316 0%,#ea580c 100%);background-color:#ea580c;border-radius:12px;box-shadow:0 8px 16px rgba(234,88,12,0.3);border:none;width:auto;max-width:95%;"><tbody><tr><td align="center" style="padding:16px 36px;background:linear-gradient(90deg,#f97316 0%,#ea580c 100%);background-color:#ea580c;border-radius:12px;border:none;text-align:center;"><a href="${affiliateLink}" target="_blank" style="display:block;text-decoration:none;color:#ffffff;font-weight:800;font-size:18px;font-family:'Malgun Gothic','Apple SD Gothic Neo',sans-serif;"><strong style="color:#ffffff;font-weight:800;"><font color="#ffffff" style="font-size:18px;font-weight:bold;font-family:'Malgun Gothic','Apple SD Gothic Neo',sans-serif;">🔥 [제품명] 특가 혜택 및 상세 정보 확인하러 가기 ➔</font></strong></a></td></tr></tbody></table>

[블로그 스타일 지정]
현재 선택된 작문 스타일은 [${style}] 입니다.
- review: 5단계 고전환율 포스팅 (공감대 유발 -> 선택 기준 설명 -> 장단점 솔직 요약 -> 삶의 시각적 변화 -> 추천 및 링크)
- comparison: 유사 스펙 제품군과의 핵심 비교 포인트 중심 리뷰
- story: 친근한 수다방 형식의 솔직 담백 사용기 스토리텔링

[공통 링크 규칙 및 기타]
- **본문 중간 제품 링크 필수 삽입**: 독자의 구매 전환율을 높이기 위해, 글의 전개 흐름상 가장 설득력이 높아지는 중간 부분(예: 핵심 스펙 설명 직후, 극복 팁 소개 후)에 제휴 링크(${affiliateLink})를 눈에 띄는 박스/버튼 형태로 최소 1~2회 삽입하세요. (네이버 블로그 복사 붙여넣기 시 서식이 깨지는 것을 방지하기 위해 반드시 아래 예시와 같이 <table> 태그를 활용한 버튼 구조를 그대로 작성해야 합니다.) HTML 예시:
  <table align="center" style="border-collapse:collapse;margin:30px auto;background:linear-gradient(90deg,#2563eb 0%,#1d4ed8 100%);background-color:#2563eb;border-radius:50px;box-shadow:0 8px 16px rgba(37,99,235,0.25);border:none;width:auto;max-width:95%;"><tbody><tr><td align="center" style="padding:14px 32px;background:linear-gradient(90deg,#2563eb 0%,#1d4ed8 100%);background-color:#2563eb;border-radius:50px;border:none;text-align:center;"><a href="${affiliateLink}" target="_blank" style="display:block;text-decoration:none;color:#ffffff;font-weight:800;font-size:17px;font-family:'Malgun Gothic','Apple SD Gothic Neo',sans-serif;"><strong style="color:#ffffff;font-weight:800;"><font color="#ffffff" style="font-size:17px;font-weight:bold;font-family:'Malgun Gothic','Apple SD Gothic Neo',sans-serif;">👉 지금 바로 [제품명] 할인가 확인하기 ➔</font></strong></a></td></tr></tbody></table>
- **링크 변조 금지**: 전달된 쿠팡 공식 숏링크(${affiliateLink})만을 변조나 환각 없이 정확하게 출력하세요. HTML <a> 태그를 사용해야 합니다.
${imageInstruction}
`;

    const userPrompt = `
[상품 정보 데이터]
- 상품명: ${productData.title}
- 카테고리: ${productData.categoryLabel || productData.category}
- 판매 가격: ${productData.price || '가격정보 확인불가'}
- 판매자/배송: ${productData.author}
- 선택 옵션 정보: ${optionDescriptions}
- 제품 상세 설명 요약:
${productData.content}

위 상품 정보를 바탕으로 제공된 지침에 따라 검색 포털 저품질 우회가 가능한 최고 수준의 포스팅을 작성해 주세요.
`;

    const payload = {
      contents: [{
        parts: [{
          text: systemPrompt + '\n\n' + userPrompt
        }]
      }]
    };

    const response = await fetch(endpoint, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(payload)
    });

    if (!response.ok) {
      const errData = await response.json().catch(() => ({}));
      const errMsg = errData.error?.message || `HTTP ${response.status}`;
      throw new Error(`Gemini API 호출 실패: ${errMsg}`);
    }

    const resJson = await response.json();
    const responseText = resJson.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!responseText) {
      throw new Error('API 응답 형식이 올바르지 않거나 빈 원고가 반환되었습니다.');
    }

    // Parse Title & Body
    let title = '블로그 제목';
    let body = responseText;

    if (responseText.includes('[제목]') && responseText.includes('[BLOGSPOT_START]')) {
      const titleSplit = responseText.split('[BLOGSPOT_START]');
      title = titleSplit[0].replace('[제목]', '').trim();
      body = titleSplit[1] ? titleSplit[1].replace('[BLOGSPOT_END]', '').trim() : responseText;
    } else if (responseText.includes('[본문]')) {
      const parts = responseText.split('[본문]');
      title = parts[0].replace('[제목]', '').replace(/---/g, '').trim();
      body = parts[1] ? parts[1].trim() : responseText;
    } else if (responseText.includes('---')) {
      const parts = responseText.split('---');
      title = parts[0].replace('[제목]', '').trim();
      body = parts.slice(1).join('---').trim();
    }

    return {
      title,
      body,
      raw: responseText
    };
  }

  /**
   * Call Google Gemini API to generate Threads viral posts (separated into main post and comment thread)
   */
  async function generateThreadsPost(productData, style = 'hook', customLink = '') {
    const key = getGeminiKey();
    if (!key) {
      throw new Error('Gemini API Key가 설정되지 않았습니다. 상단 입력창에 등록해 주세요.');
    }

    const model = 'gemini-3.5-flash';
    const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${key}`;

    const optionDescriptions = productData.options && productData.options.length > 0
      ? productData.options.join(', ')
      : '없음';

    const affiliateLink = customLink.trim() || productData.link || '#';

    const imageUrls = productData.images && productData.images.length > 0
      ? productData.images.slice(0, 10) // Use up to 10 main images
      : [];

    const isToss = productData.platform === 'toss' || (affiliateLink && affiliateLink.includes('toss.im'));
    const disclosureText = isToss 
      ? "이 포스팅은 토스쇼핑 쉐어링크 활동의 일환으로, 이에 따른 일정액의 수수료를 제공받습니다."
      : "이 포스팅은 쿠팡 파트너스 활동의 일환으로, 이에 따른 일정액의 수수료를 제공받습니다.";

    const systemPrompt = `
당신은 20년 경력의 전문 블로거이자 SEO/AEO/GEO 전문가, 그리고 SNS 마케팅 카피라이팅 전문가입니다. 제공된 상품 정보를 분석하여 고전환율을 이끌어내는 글을 작성하세요.
철저히 기계적인 번역투나 딱딱한 인공지능 말투(예: '도움이 되셨길 바랍니다', '이상으로', '자, 시작해볼까요?' 등)를 금지하고, 실제 이웃이 써보고 친근하게 추천해주는 듯한 구어체로 작성하세요.

반드시 아래 출력 형식을 정확하게 지켜주세요:
[THREADS_START]
여기에 스레드 본문 작성
[THREADS_END]
===
[댓글]
여기에 스레드 댓글(타래) 내용 작성

[스레드 (Threads) 지침]
- 전체 70%는 자연스럽고 인간미 넘치는 수다/에피소드로 채우고, 30%만 유용한 제품 정보로 구성합니다.
- 첫 줄은 시선을 끄는 '더보기' 유도 바이럴 후킹 공식(숫자+약속, 의외성, 폭로/비밀, 감정공감 스토리)을 활용하여 흥미진진하게 시작합니다.
- 본문은 줄바꿈과 대괄호([...]) 또는 번호 리스트를 활용해 가독성을 높입니다.
- 본문 중간에는 구매 링크를 절대 넣지 않습니다. 해시태그 아래 맨 마지막에만 제휴 고지, 클릭 유도 문구, 공식 쿠팡 숏링크를 줄바꿈 형식으로 붙입니다. (아래 댓글/타래 규칙 참조)
- 마지막 부분에는 답글(Reply)을 많이 유도할 수 있는 매력적이고 직관적인 질문(양자택일 등)을 던져 댓글 작성을 강력하게 활성화시킵니다.
- 말투: 100% 날것의 구어체, 인터넷 신조어, 급식체, 말줄임표(..) 및 적절한 이모지를 사용하여 매우 친근하고 자연스러운 소셜미디어 말투로 작성하세요.

[스레드 본문(노링크) 작성 규칙]
1. 본문 내 링크 절대 삽입 금지 (알고리즘 노출 제한 우회용).
2. 분량 제한: 한글 기준 공백 포함 150자 내외로 매우 짧고 컴팩트하게 작성하세요.

[스레드 댓글/타래 작성 규칙]
1. 최상단 공정위 문구 의무 결합: 반드시 첫 줄에 다음 문구를 토씨 하나 틀리지 말고 정확하게 배치하세요:
"${disclosureText}"
2. 한 줄 후킹 요약: 그 바로 아래에 제품에 대한 한 줄 후킹 요약을 작성하세요.
3. 제휴 단축 링크: 맨 끝에 반드시 전달된 공식 숏링크(${affiliateLink})만을 변조나 환각 없이 정확하게 출력하세요.
`;

    const userPrompt = `
[선택된 스타일] : ${style} (hook: 자극적 후킹, tip: 정보/꿀팁 요약, chat: 일상 썰 수다체)
[상품 정보 데이터]
- 상품명: ${productData.title}
- 판매 가격: ${productData.price || '가격정보 확인불가'}
- 판매자/배송: ${productData.author}
- 선택 옵션 정보: ${optionDescriptions}
- 제품 상세 설명 요약:
${productData.content}

위 정보를 바탕으로 스레드 알고리즘을 터트릴 수 있는 매력적인 바이럴 본문과 댓글 세트를 작성해 주세요.
`;

    const payload = {
      contents: [{
        parts: [{
          text: systemPrompt + '\n\n' + userPrompt
        }]
      }]
    };

    const response = await fetch(endpoint, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(payload)
    });

    if (!response.ok) {
      const errData = await response.json().catch(() => ({}));
      const errMsg = errData.error?.message || `HTTP ${response.status}`;
      throw new Error(`Gemini API 호출 실패: ${errMsg}`);
    }

    const resJson = await response.json();
    const responseText = resJson.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!responseText) {
      throw new Error('API 응답 형식이 올바르지 않거나 빈 원고가 반환되었습니다.');
    }

    let mainPost = '스레드 본문';
    let replyPost = '스레드 댓글';

    if (responseText.includes('===') && responseText.includes('[THREADS_START]')) {
      const parts = responseText.split('===');
      mainPost = parts[0].replace('[THREADS_START]', '').replace('[THREADS_END]', '').trim();
      replyPost = parts[1] ? parts[1].replace('[댓글]', '').trim() : responseText;
    } else if (responseText.includes('===')) {
      const parts = responseText.split('===');
      mainPost = parts[0].replace('[본문]', '').replace(/\[댓글\]/g, '').trim();
      replyPost = parts[1] ? parts[1].replace('[댓글]', '').trim() : responseText;
    } else if (responseText.includes('[댓글]')) {
      const parts = responseText.split('[댓글]');
      mainPost = parts[0].replace('[본문]', '').trim();
      replyPost = parts[1] ? parts[1].trim() : responseText;
    }

    return {
      main: mainPost,
      reply: replyPost,
      raw: responseText
    };
  }

  // Export to global context
  global.AIBlogClient = {
    getGeminiKey,
    saveGeminiKey,
    generatePost,
    generateThreadsPost,
    mdToHtml
  };
})(typeof self !== 'undefined' ? self : (typeof window !== 'undefined' ? window : this));
